#!/bin/sh
# set -e
uv run python evaluate.py --model gpt2 --transcoder_path ../e2e/checkpoints/clt-gpt2/coal-per-k8
uv run python evaluate.py --model gpt2 --transcoder_path ../e2e/checkpoints/clt-gpt2/const-k8
uv run python evaluate.py --model gpt2 --transcoder_path ../e2e/checkpoints/clt-gpt2/no-clt
uv run python evaluate.py --model gpt2 --transcoder_path ../e2e/checkpoints/clt-gpt2/coal
uv run python evaluate.py --model gpt2 --transcoder_path ../sparsify/checkpoints/clt-gpt2/new-run


# uv run python evaluate.py --transcoder_path ../e2e/checkpoints/gelu-4l-clt/ef128k64
# uv run python evaluate.py --transcoder_path ../e2e/checkpoints/gelu-4l-clt/ef128k64_
# uv run python evaluate.py --transcoder_path ../e2e/checkpoints/gelu-4l-clt/k64
# uv run python evaluate.py --transcoder_path ../e2e/checkpoints/gelu-4l-nonclt/baseline
# uv run python evaluate.py --transcoder_path ../e2e/checkpoints/gelu-4l-clt-noskip/baseline
# uv run python evaluate.py --transcoder_path ../e2e/checkpoints/gelu-4l-nonclt-skip/baseline
# uv run python evaluate.py --transcoder_path ../e2e/checkpoints/gelu-4l-nonclt-skip/ef64k64
# uv run python evaluate.py --mlp_trim 50
# uv run python evaluate.py --mlp_trim 100
# uv run python evaluate.py --mlp_trim 200
# uv run python evaluate.py --mlp_trim 500
