#!/usr/bin/env bash

PROMPT_NAME="test-gpt2"
# PROMPT_NAME="basketball-llama"
# PROMPT_NAME="basketball-gemma"
# PROMPT_NAME="basketball-smollm"
# PROMPT_NAME="basketball-llama-base"
# SCAN=transcoder_llama_131k_highbs_v0
# SCAN=transcoder-llama-131k-mntss
# SCAN=bs8-lr2e-4-none-ef128-k16
SCAN=bs8-lr3e-4-tied-ef128-k16
# SCAN=gemmascope
# SCAN=transcoder_llama_131k_mntss_kl
# SCAN=transcoder-llama-131k-adam-kl
# SCAN=transcoder-llama-131k-adam-kl
# SCAN=transcoder-llama-131k-adam-highbs
# SCAN=smollm-v1
set -e
# PROMPT_TEXT="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
PROMPT_TEXT="<|endoftext|>What is Michael Jordan's name? Michael Jordan's name is"
uv run python -m attribute \
--cache_path=results/$SCAN/latents \
--name $PROMPT_NAME \
--scan "$SCAN" \
"$PROMPT_TEXT" \
$@ \
--transcoder_path="/mnt/ssd-1/nev/e2e/checkpoints/gpt2-sweep/$SCAN" --model_name="openai-community/gpt2" --remove_prefix 1 \
# --transcoder_path="results/llama-mntss-relu" --model_name="meta-llama/Llama-3.2-1B" --remove_prefix 1 --pre_ln_hook=True --force_k=512 --filter_high_freq_early=0.0
# --transcoder_path="results/gemma-scope-2b-pt-transcoders" --model_name="google/gemma-2-2b" --remove_prefix 1 --post_ln_hook=True \
# --transcoder_path="/mnt/ssd-1/nev/e2e/checkpoints/llama/adam-highbs" --model_name="meta-llama/Llama-3.2-1B" --remove_prefix 1 \
# --transcoder_path="/mnt/ssd-1/nev/e2e/checkpoints/smollm/k32" --model_name="HuggingFaceTB/SmolLM2-135M" \
# --transcoder_path="/mnt/ssd-1/nev/e2e/checkpoints/llama/anneal-adam" --model_name="meta-llama/Llama-3.2-1B" --remove_prefix 1 \
# --transcoder_path="/mnt/ssd-1/nev/sparsify/checkpoints/llama-finetune/adam" --model_name="meta-llama/Llama-3.2-1B" --remove_prefix 1 \
# --transcoder_path="/mnt/ssd-1/nev/e2e/checkpoints/llama/anneal-adam" --model_name="meta-llama/Llama-3.2-1B" --remove_prefix 1 \
# --transcoder_path="/mnt/ssd-1/nev/sparsify/checkpoints/llama-finetune-rmid/kl" --model_name="meta-llama/Llama-3.2-1B" --remove_prefix 1 --pre_ln_hook=True \
# --transcoder_path="/mnt/ssd-1/nev/e2e/checkpoints/smollm" --model_name="HuggingFaceTB/SmolLM2-135M" \
# --pre_ln_hook=True
# --transcoder_path="/mnt/ssd-1/nev/sparsify/checkpoints/llama/high-bs" \

# --transcoder_path="EleutherAI/skip-transcoder-Llama-3.2-1B-131k" \
exit


PROMPT_NAME="basketball-gpt2"
PROMPT_TEXT="<|endoftext|>What sport does Michael Jordan play? Michael Jordan plays the sport of"
uv run python -m attribute --model_name="gpt2" \
--transcoder_path="/mnt/ssd-1/nev/sparsify/checkpoints/clt-gpt2-finetune/ft-test-0" \
--cache_path=results/transcoder_gpt2_128x_const_k16_ft_v0/latents \
--name $PROMPT_NAME \
--scan "gpt2-128x-const-k16-ft-v0" \
--remove_prefix 1 \
"$PROMPT_TEXT"
exit

uv run python -m attribute --model_name="nev/GELU_4L512W_C4_Code" \
--transcoder_path="../e2e/checkpoints/gelu-4l-clt/ef128k64" \
--cache_path=results/transcoder_gelu4l_x128k64-0/latents \
--name "test-1-gelu4l" \
--scan "gelu-4l-x128k64-v0" \
--remove_bos True \
"<|BOS|>The National Digital Analytics Group ("
exit

CUDA_VISIBLE_DEVICES=1 uv run python -m attribute --model_name="nev/acronym-toy-3M" \
--transcoder_path="../e2e/checkpoints/acr-clt/test" \
--cache_path=results/transcoder_acr/latents \
--name "test-1-acr" \
--scan "acr-new-test" \
"National Dome Automatic Graph ("
exit

ATT='uv run python -m attribute --model_name="roneneldan/TinyStories-33M" --transcoder_path="../e2e/checkpoints/clt-ts/ts" --cache_path=results/transcoder_128x/latents'
# $ATT --name="test-1-ts" "<|endoftext|>After falling in mud, she had a"
# $ATT --name="test-2-ts" "<|endoftext|>There was a girl called Lucy."
$ATT --name="test-3-ts" "<|endoftext|>The girl's dog had a red ball. She said \"It's color is"
$ATT --name="test-4-ts" "<|endoftext|>Once upon a time, Ada was happily walking through a magical forest with"
