#!/usr/bin/env bash
# MODEL=roneneldan/TinyStories-33M
# MODEL=nev/acronym-toy-3M
MODEL=nev/GELU_4L512W_C4_Code
# TRANSCODER=../e2e/checkpoints/clt-ts/ts
# TRANSCODER=../e2e/checkpoints/acr-clt/test
# TRANSCODER=../e2e/checkpoints/gelu-4l-clt/k64
# TRANSCODER=../e2e/checkpoints/gelu-4l-clt/ef64k64
TRANSCODER=../e2e/checkpoints/gelu-4l-nonclt-skip/ef64k64
# DATASET="--dataset_repo roneneldan/TinyStories --dataset_split train --n_tokens 10_000_000"
# DATASET="--dataset_repo nev/acronyms-toy-dataset --dataset_split train --n_tokens 10_000_000"
DATASET="--dataset_repo EleutherAI/fineweb-edu-dedup-10b --dataset_split train --n_tokens 10_000_000"
# NAME="transcoder_128x"
# NAME="transcoder_acr"
NAME="transcoder_gelu4l_x64k64-0"
# CUDA_VISIBLE_DEVICES=1 python cache.py $MODEL $TRANSCODER --num_gpus 1 $DATASET --hookpoints h.0.mlp h.1.mlp h.2.mlp h.3.mlp h.4.mlp h.5.mlp h.6.mlp h.7.mlp --name $NAME
CUDA_VISIBLE_DEVICES=0 python cache.py $MODEL $TRANSCODER --num_gpus 1 $DATASET --hookpoints h.0.mlp h.1.mlp h.2.mlp h.3.mlp --name $NAME
